services:
  web:
    image: tsgames/pms:latest
    container_name: php-apache
    build:
      .
    ports:
      - "8080:80" 
    volumes:
      - ./src:/var/www/html 
      - ./template:/var/template
      - data_images:/var/www/html/images 
      - data_db:/var/db


volumes:
  data_images:
  data_db: