name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:

  psalm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install PSALM
        run: |
          wget https://github.com/vimeo/psalm/releases/download/6.5.0/psalm.phar
          chmod +x psalm.phar
          mv psalm.phar /usr/local/bin/psalm

      - name: Run Psalm (allow failure)
        run: psalm || true


  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}  

      # Schritt 4: Build das Docker-Image
      - name: Build Docker image
        run: |
          docker build -t tsgames/pms:${{ github.sha }} .

      # Schritt 5: Push das Docker-Image
      - name: Push Docker image
        run: |
          docker push tsgames/pms:${{ github.sha }}